version: '3.3'
networks:
  unebnet:
volumes:
  erp-user-data:

services:
### Apache2 PHP 7.4.6
  uneb_spms:
    image: oworyoakim/uneb_spms:v6
    container_name: ${SPMS_CACHE_KEY}
    restart: always
    environment:
      APP_NAME: UNEB-SPMS
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${SPMS_APP_BASE_URL}
      APP_URL: 'http://${SPMS_APP_BASE_URL}:${SPMS_PORT}'
      APP_DEBUG: ${APP_DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      CACHE_KEY: ${SPMS_CACHE_KEY}
      DB_HOST: ${SPMS_DB_HOST}
      DB_DATABASE: ${SPMS_DB_DATABASE}
      DB_USERNAME: ${SPMS_DB_USERNAME}
      DB_PASSWORD: ${SPMS_DB_PASSWORD}
      CACHE_DRIVER: file
      QUEUE_CONNECTION: database
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048m
          cpus: "1.5"
        reservations:
          memory: 1536m
          cpus: "1.0"
      #volumes:
      #- /var/www/html/erp/storage/:/var/www/html/storage/
    ports:
      - "${SPMS_PORT}:80"
    networks:
      - unebnet
  uneb_hrms:
    image: oworyoakim/uneb_hrms:v6
    container_name: ${HRMS_CACHE_KEY}
    restart: always
    environment:
      APP_NAME: UNEB-HRMS
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${HRMS_APP_BASE_URL}
      APP_URL: 'http://${HRMS_APP_BASE_URL}:${HRMS_PORT}'
      APP_DEBUG: ${APP_DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      CACHE_KEY: ${HRMS_CACHE_KEY}
      DB_HOST: ${HRMS_DB_HOST}
      DB_DATABASE: ${HRMS_DB_DATABASE}
      DB_USERNAME: ${HRMS_DB_USERNAME}
      DB_PASSWORD: ${HRMS_DB_PASSWORD}
      CACHE_DRIVER: file
      QUEUE_CONNECTION: database
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048m
          cpus: "1.5"
        reservations:
          memory: 1536m
          cpus: "1.0"
    #volumes:
      #- /var/www/html/erp/:/var/www/html/public/storage/:rw
    ports:
      - "${HRMS_PORT}:80"
    networks:
      - unebnet
  uneb_erp:
    image: oworyoakim/uneb_erp:v6
    container_name: ${CACHE_KEY}
    restart: always
    depends_on:
      - uneb_hrms
      - uneb_spms
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${APP_BASE_URL}
      APP_URL: ${APP_URL}
      APP_DEBUG: ${APP_DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      CACHE_KEY: ${CACHE_KEY}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: '${DB_PASSWORD}'
      TINYMCE_API_KEY: ${TINYMCE_API_KEY}
      HRMS_APP_URL: 'http://${HRMS_APP_BASE_URL}:${HRMS_PORT}'
      SPMS_APP_URL: 'http://${SPMS_APP_BASE_URL}:${SPMS_PORT}'
      CACHE_DRIVER: file
      QUEUE_CONNECTION: database
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048m
          cpus: "1.5"
        reservations:
          memory: 1536m
          cpus: "1.0"
    #volumes:
      #- /var/www/html/erp/:/var/www/html/public/storage/:rw
      #- /var/www/html/erp/logs/:/var/www/html/storage/logs/:rw
    ports:
      - "${APP_PORT}:80"
    networks:
      - unebnet

