version: '3.7'
networks:
  unebnet:

services:
### Apache2 PHP 7.4.6
  uneb_spms:
    image: oworyoakim/uneb_spms:latest
    container_name: ${SPMS_CACHE_KEY}
    restart: always
    environment:
      APP_NAME: UNEB-SPMS
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${SPMS_APP_BASE_URL}
      APP_URL: ${SPMS_APP_URL}
      APP_DEBUG: ${APP_DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      CACHE_KEY: ${SPMS_CACHE_KEY}
      DB_HOST: ${SPMS_DB_HOST}
      DB_DATABASE: ${SPMS_DB_DATABASE}
      DB_USERNAME: ${SPMS_DB_USERNAME}
      DB_PASSWORD: ${SPMS_DB_PASSWORD}
      CACHE_DRIVER: file
      QUEUE_CONNECTION: database
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048m
          cpus: "1.5"
        reservations:
          memory: 1536m
          cpus: "1.0"
      #volumes:
      #- /var/www/html/erp/storage/:/var/www/html/storage/
    ports:
      - "${SPMS_PORT}:80"
    networks:
      - unebnet
  uneb_hrms:
    image: oworyoakim/uneb_hrms:latest
    container_name: ${HRMS_CACHE_KEY}
    restart: always
    environment:
      APP_NAME: UNEB-HRMS
      APP_ENV: ${APP_ENV}
      APP_BASE_URL: ${HRMS_APP_BASE_URL}
      APP_URL: ${HRMS_APP_URL}
      APP_DEBUG: ${APP_DEBUG}
      TIME_ZONE: ${TIME_ZONE}
      CACHE_KEY: ${HRMS_CACHE_KEY}
      DB_HOST: ${HRMS_DB_HOST}
      DB_DATABASE: ${HRMS_DB_DATABASE}
      DB_USERNAME: ${HRMS_DB_USERNAME}
      DB_PASSWORD: ${HRMS_DB_PASSWORD}
      CACHE_DRIVER: file
      QUEUE_CONNECTION: database
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048m
          cpus: "1.5"
        reservations:
          memory: 1536m
          cpus: "1.0"
    #volumes:
      #- /var/www/html/erp/storage/:/var/www/html/storage/
    ports:
      - "${HRMS_PORT}:80"
    networks:
      - unebnet

