const routes = {
    DASHBOARD: '/dashboard',
    DASHBOARD_STATISTICS_HRMS: '/hrms/dashboard/statistics',
    DIRECTORATES: '/directorates',
    DIRECTORATES_JSON: '/directorates/all-json',
    DEPARTMENTS: '/departments',
    DEPARTMENTS_JSON: '/departments/all-json',
    DIVISIONS: '/divisions',
    DIVISIONS_JSON: '/divisions/all-json',
    SECTIONS: '/sections',
    SECTIONS_JSON: '/sections/all-json',
    DESIGNATIONS: '/designations',
    DESIGNATIONS_JSON: '/designations/all-json',
    SALARY_SCALES: '/salary-scales',
    SALARY_SCALES_JSON: '/salary-scales/all-json',
    LEAVES: '/leaves',
    LEAVES_JSON: '/leaves/all-json',
    LEAVE_TYPES: '/leaves/types',
    LEAVE_TYPES_JSON: '/leaves/types/all-json',
    LEAVE_POLICIES: '/leaves/types/policies',
    LEAVE_APPLICATIONS: '/leave-applications',
    LEAVE_APPLICATIONS_JSON: '/leave-applications/all-json',
    LEAVE_APPLICATION_STATUSES: '/leave-applications/statuses',
    LEAVE_APPLICATION_STATUSES_JSON: '/leave-applications/statuses/all-json',
    EMPLOYEES: '/employees',
    EMPLOYEES_JSON: '/employees/all-json',
    EMPLOYEES_TITLES: '/employees/titles',
    EMPLOYEES_GENDERS: '/employees/genders',
    EMPLOYEES_RELIGIONS: '/employees/religions',
    EMPLOYEES_MARITAL_STATUSES: '/employees/marital-statuses',
    EMPLOYEE_STATUSES: '/employees/employee-statuses',
    EMPLOYMENT_STATUSES: '/employees/employment-statuses',
    EMPLOYMENT_TERMS: '/employees/employment-terms',
    EMPLOYMENT_TYPES: '/employees/employment-types',
    EMPLOYEES_RELATIONSHIPS: '/employees/relationships',
    EMPLOYEES_RELATED_PERSONS: '/employees/related-persons',
    EMPLOYEES_EXPERIENCE: '/employees/experience',
    EMPLOYEES_EDUCATION: '/employees/education',
    EMPLOYEES_ATTRIBUTES: '/form-selections-options',
    EMPLOYEES_PROFILE: '/employees/profile',
    EMPLOYEE_DOCUMENTS: '/documents',
    GENERAL_SETTINGS: '/settings/general',
    GENERAL_SETTINGS_JSON: '/settings/general/all-json',
    APPROVAL_SETTINGS: '/settings/approvals',
    DELEGATIONS: '/delegations',

    // SPMS
    DASHBOARD_STATISTICS_SPMS: '/spms/dashboard/statistics',
    PLANS: '/spms/plans',
    OBJECTIVES: '/spms/objectives',
    SWOTS: '/spms/swots',
    SWOTCATEGORIES: '/spms/swots',
};

export default routes;
