const routes = {
    // GENERAL
    USERS: '/users',
    ROLES: '/roles',
    GENERAL_SETTINGS: '/settings/general',
    GENERAL_SETTINGS_JSON: '/settings/general/all-json',
    // hrms
    DASHBOARD: '/hrms/dashboard',
    DASHBOARD_STATISTICS_HRMS: '/hrms/dashboard/statistics',
    DIRECTORATES: '/hrms/directorates',
    DIRECTORATES_JSON: '/hrms/directorates/all-json',
    DEPARTMENTS: '/hrms/departments',
    DEPARTMENTS_JSON: '/hrms/departments/all-json',
    DIVISIONS: '/hrms/divisions',
    DIVISIONS_JSON: '/hrms/divisions/all-json',
    SECTIONS: '/hrms/sections',
    SECTIONS_JSON: '/hrms/sections/all-json',
    DESIGNATIONS: '/hrms/designations',
    DESIGNATIONS_JSON: '/hrms/designations/all-json',
    SALARY_SCALES: '/hrms/salary-scales',
    SALARY_SCALES_JSON: '/hrms/salary-scales/all-json',
    LEAVES: '/hrms/leaves',
    LEAVES_JSON: '/hrms/leaves/all-json',
    LEAVE_TYPES: '/hrms/leaves/types',
    LEAVE_TYPES_JSON: '/hrms/leaves/types/all-json',
    LEAVE_POLICIES: '/hrms/leaves/types/policies',
    LEAVE_APPLICATIONS: '/hrms/leave-applications',
    LEAVE_APPLICATIONS_JSON: '/hrms/leave-applications/all-json',
    LEAVE_APPLICATION_STATUSES: '/hrms/leave-applications/statuses',
    LEAVE_APPLICATION_STATUSES_JSON: '/hrms/leave-applications/statuses/all-json',
    EMPLOYEES: '/hrms/employees',
    EMPLOYEES_JSON: '/hrms/employees/all-json',
    EMPLOYEES_TITLES: '/employees/titles',
    EMPLOYEES_GENDERS: '/hrms/employees/genders',
    EMPLOYEES_RELIGIONS: '/hrms/employees/religions',
    EMPLOYEES_MARITAL_STATUSES: '/hrms/employees/marital-statuses',
    EMPLOYEE_STATUSES: '/hrms/employees/employee-statuses',
    EMPLOYMENT_STATUSES: '/hrms/employees/employment-statuses',
    EMPLOYMENT_TERMS: '/hrms/employees/employment-terms',
    EMPLOYMENT_TYPES: '/hrms/employees/employment-types',
    EMPLOYEES_RELATIONSHIPS: '/hrms/employees/relationships',
    EMPLOYEES_RELATED_PERSONS: '/hrms/employees/related-persons',
    EMPLOYEES_EXPERIENCE: '/hrms/employees/experience',
    EMPLOYEES_EDUCATION: '/hrms/employees/education',
    EMPLOYEES_ATTRIBUTES: '/hrms/form-selections-options',
    EMPLOYEES_PROFILE: '/hrms/employees/profile',
    EMPLOYEE_DOCUMENTS: '/hrms/documents',
    APPROVAL_SETTINGS: '/hrms/settings/approvals',
    DELEGATIONS: '/hrms/delegations',

    // SPMS
    DASHBOARD_STATISTICS_SPMS: '/spms/dashboard/statistics',
    PLANS: '/spms/plans',
    SWOTS: '/spms/swots',
    SWOT_CATEGORIES: '/spms/swot-categories',

    OBJECTIVES: '/spms/objectives',
    INTERVENTIONS: '/spms/interventions',
    OUTPUTS: '/spms/outputs',
    OUTPUT_INDICATORS: '/spms/output-indicators',
    OUTPUT_TARGETS: '/spms/output-indicator-targets',
    OUTPUT_ACHIEVEMENTS: '/spms/output-achievements',

    KEY_RESULT_AREAS: '/spms/key-result-areas',
    OUTCOMES: '/spms/outcomes',
    OUTCOME_INDICATORS: '/spms/outcome-indicators',
    OUTCOME_TARGETS: '/spms/outcome-indicator-targets',
    OUTCOME_ACHIEVEMENTS: '/spms/outcome-achievements',
    WORK_PLANS: '/spms/work-plans',
    ACTIVITIES: '/spms/activities',
    STAGES: '/spms/stages',
};

export default routes;
